/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise {
  'name' : string,
  'equipmentType' : string,
  'muscleGroup' : string,
}
export type Time = bigint;
export interface WeightEntry {
  'weight' : bigint,
  'exerciseId' : bigint,
  'date' : Time,
  'reps' : bigint,
  'sets' : bigint,
  'workoutId' : [] | [bigint],
}
export interface Workout {
  'id' : bigint,
  'exerciseIds' : Array<bigint>,
  'name' : string,
  'createdAt' : Time,
}
export interface _SERVICE {
  'createExercise' : ActorMethod<[string, string, string], bigint>,
  'createWorkout' : ActorMethod<[string, Array<bigint>], bigint>,
  'deleteExercise' : ActorMethod<[bigint], undefined>,
  'deleteWorkout' : ActorMethod<[bigint], undefined>,
  'filterExercisesByEquipmentType' : ActorMethod<[string], Array<Exercise>>,
  'filterExercisesByMuscleGroup' : ActorMethod<[string], Array<Exercise>>,
  'getAllExercisesSorted' : ActorMethod<[], Array<Exercise>>,
  'getExercise' : ActorMethod<[bigint], Exercise>,
  'getWeightProgress' : ActorMethod<[bigint], Array<WeightEntry>>,
  'getWorkout' : ActorMethod<[bigint], Workout>,
  'logWeightEntry' : ActorMethod<
    [bigint, bigint, bigint, bigint, [] | [bigint]],
    bigint
  >,
  'seedExercises' : ActorMethod<[], undefined>,
  'updateExercise' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateWorkout' : ActorMethod<[bigint, string, Array<bigint>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];