/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'equipmentType' : IDL.Text,
  'muscleGroup' : IDL.Text,
});
export const Time = IDL.Int;
export const WeightEntry = IDL.Record({
  'weight' : IDL.Nat,
  'exerciseId' : IDL.Nat,
  'date' : Time,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'workoutId' : IDL.Opt(IDL.Nat),
});
export const Workout = IDL.Record({
  'id' : IDL.Nat,
  'exerciseIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  'createExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createWorkout' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'deleteExercise' : IDL.Func([IDL.Nat], [], []),
  'deleteWorkout' : IDL.Func([IDL.Nat], [], []),
  'filterExercisesByEquipmentType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'filterExercisesByMuscleGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getAllExercisesSorted' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getExercise' : IDL.Func([IDL.Nat], [Exercise], ['query']),
  'getWeightProgress' : IDL.Func([IDL.Nat], [IDL.Vec(WeightEntry)], ['query']),
  'getWorkout' : IDL.Func([IDL.Nat], [Workout], ['query']),
  'logWeightEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'updateExercise' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateWorkout' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'equipmentType' : IDL.Text,
    'muscleGroup' : IDL.Text,
  });
  const Time = IDL.Int;
  const WeightEntry = IDL.Record({
    'weight' : IDL.Nat,
    'exerciseId' : IDL.Nat,
    'date' : Time,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'workoutId' : IDL.Opt(IDL.Nat),
  });
  const Workout = IDL.Record({
    'id' : IDL.Nat,
    'exerciseIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    'createExercise' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createWorkout' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'deleteExercise' : IDL.Func([IDL.Nat], [], []),
    'deleteWorkout' : IDL.Func([IDL.Nat], [], []),
    'filterExercisesByEquipmentType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'filterExercisesByMuscleGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getAllExercisesSorted' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getExercise' : IDL.Func([IDL.Nat], [Exercise], ['query']),
    'getWeightProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WeightEntry)],
        ['query'],
      ),
    'getWorkout' : IDL.Func([IDL.Nat], [Workout], ['query']),
    'logWeightEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'updateExercise' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateWorkout' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };