/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    name: string;
    equipmentType: string;
    muscleGroup: string;
}
export type Time = bigint;
export interface Workout {
    id: bigint;
    exerciseIds: Array<bigint>;
    name: string;
    createdAt: Time;
}
export interface WeightEntry {
    weight: bigint;
    exerciseId: bigint;
    date: Time;
    reps: bigint;
    sets: bigint;
    workoutId?: bigint;
}
export interface backendInterface {
    createExercise(name: string, equipmentType: string, muscleGroup: string): Promise<bigint>;
    createWorkout(name: string, exerciseIds: Array<bigint>): Promise<bigint>;
    deleteExercise(id: bigint): Promise<void>;
    deleteWorkout(id: bigint): Promise<void>;
    filterExercisesByEquipmentType(equipmentType: string): Promise<Array<Exercise>>;
    filterExercisesByMuscleGroup(muscleGroup: string): Promise<Array<Exercise>>;
    getAllExercisesSorted(): Promise<Array<Exercise>>;
    getExercise(id: bigint): Promise<Exercise>;
    getWeightProgress(exerciseId: bigint): Promise<Array<WeightEntry>>;
    getWorkout(id: bigint): Promise<Workout>;
    logWeightEntry(exerciseId: bigint, weight: bigint, reps: bigint, sets: bigint, workoutId: bigint | null): Promise<bigint>;
    seedExercises(): Promise<void>;
    updateExercise(id: bigint, name: string, equipmentType: string, muscleGroup: string): Promise<void>;
    updateWorkout(id: bigint, name: string, exerciseIds: Array<bigint>): Promise<void>;
}
import type { Time as _Time, WeightEntry as _WeightEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createExercise(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createExercise(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExercise(arg0, arg1, arg2);
            return result;
        }
    }
    async createWorkout(arg0: string, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkout(arg0, arg1);
            return result;
        }
    }
    async deleteExercise(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return result;
        }
    }
    async deleteWorkout(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkout(arg0);
            return result;
        }
    }
    async filterExercisesByEquipmentType(arg0: string): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterExercisesByEquipmentType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterExercisesByEquipmentType(arg0);
            return result;
        }
    }
    async filterExercisesByMuscleGroup(arg0: string): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterExercisesByMuscleGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterExercisesByMuscleGroup(arg0);
            return result;
        }
    }
    async getAllExercisesSorted(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercisesSorted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercisesSorted();
            return result;
        }
    }
    async getExercise(arg0: bigint): Promise<Exercise> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercise(arg0);
            return result;
        }
    }
    async getWeightProgress(arg0: bigint): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightProgress(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightProgress(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkout(arg0: bigint): Promise<Workout> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkout(arg0);
            return result;
        }
    }
    async logWeightEntry(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logWeightEntry(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWeightEntry(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async seedExercises(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedExercises();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedExercises();
            return result;
        }
    }
    async updateExercise(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExercise(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExercise(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateWorkout(arg0: bigint, arg1: string, arg2: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkout(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkout(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_WeightEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeightEntry): WeightEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    exerciseId: bigint;
    date: _Time;
    reps: bigint;
    sets: bigint;
    workoutId: [] | [bigint];
}): {
    weight: bigint;
    exerciseId: bigint;
    date: Time;
    reps: bigint;
    sets: bigint;
    workoutId?: bigint;
} {
    return {
        weight: value.weight,
        exerciseId: value.exerciseId,
        date: value.date,
        reps: value.reps,
        sets: value.sets,
        workoutId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.workoutId))
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeightEntry>): Array<WeightEntry> {
    return value.map((x)=>from_candid_WeightEntry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
